### PR TITLE
Fixes bug with serialized access-token

### PR DESCRIPTION
**Pull request by Kit-kat1**
## Description

``` php
``

## Related Issue
<!--- This project only accepts pull requests related to open issues -->
<!--- If suggesting a new feature or change, please discuss it in an issue first -->
<!--- If fixing a bug, there should be an issue describing it with steps to reproduce -->
<!--- Please link to the issue here: -->

## Motivation and Context
<!--- Why is this change required? What problem does it solve? -->

## How Has This Been Tested?
<!--- Please describe in detail how you tested your changes. -->
<!--- Include details of your testing environment, and the tests you ran to -->
<!--- see how your change affects other areas of the code, etc. -->

## Screenshots (if appropriate):

## Types of changes
<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] This PR is on the ``develop`` branch.
- [ ] My code follows the code style of this project. (run `php vendor/bin/phpcs`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the **CHANGELOG** document.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
```

### CODE REVIEW

**Comment by hassankhan** [comment]
Hi, thanks for the PR! Could you rebase it on `develop` please? Thanks! 👍

**Comment by Kit-kat1** [comment]
Yeah, already done.

**Comment by hassankhan** [comment]
I don't see it, it still shows it as pointing to `master`

**Comment by Kit-kat1** [comment]
Please explain, because I don't understand what you want. 
According this image - my branch is on develop point http://imgur.com/a/5PEKQ.

**Comment by hassankhan** [comment]
screen shot 2016-09-17 at 20 33 32

It seems like the changes you've made are on the `master` branch, at least from my side.

**Comment by Kit-kat1** [comment]
Ah, ok. I will make new pull request.

**Pull request closed without merging**
