### PR TITLE
Update php version constraint

### PR DESCRIPTION
**Pull request by vinkla**
We can be more specific with the php version constraint.

### CODE REVIEW

**Comment by hassankhan** [comment]
Seems like `static` needs to be changed to `self` in `AbstractMiddleware::create()` -  quite weird that it works on the latest PHP 5.5 but not specifically 5.5.9 :confused: 

Thanks for the first PR!

**Comment by vinkla** [comment]
Yeah, do you've an idea how we can go around this?

**Comment by hassankhan** [comment]
Do you have a Gitter account? I'm on there right now: https://gitter.im/hassankhan/instagram-sdk

**Comment by vinkla** [comment]
The tests are passing now :+1:

**Comment by hassankhan** [comment]
Haha yeah, quite happy about that!

**Pull request merged**
